### ISSUE TITLE
Doesn't work with square production environment, only sandbox 

### ISSUE THREAD

**Issue by Ryanklingert** [weareseeed/react-square-web-payments-sdk#4]
### What version of React are you using?

17.02

### What version of Node.js are you using?

14.17

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

aws

### Describe the Bug

This worked well when using sandbox credentials for square, however upon trying to move over to production credentials I am getting the following error and the form does not render. 

Unhandled Promise Rejection: ApplicationIdEnvironmentMismatchError : Web Payments SDK was initialized with an application ID created in production however you are currently using sandbox.

### Expected Behavior

There should be a prop which allows the user to specify which environment they are using

### To Reproduce

Render the form using a square production applicationId

**Comment by Ryanklingert** [comment]
Resolved had to change script in head to: 
`<script type="text/javascript" src="https://web.squarecdn.com/v1/square.js"></script>`

**Comment by priyak-sdei** [comment]
Added keys but still not working

**Comment by danestves** [comment]
Hi @Ryanklingert we now provide a prop that you can pass a custom `src`

```tsx
/**
   * Override the default payment form configuration.
   *
   * Supported overrides:
   *
   * - **`scriptSrc`**: The URL of the Square payment form script.
   */
  overrides?: {
    scriptSrc?: string
  }
```

You use it in the `SquarePaymentsForm` component

**Comment by priyak-sdei** [comment]
@danestves  Now added the prop as well, but still not working.
![Screenshot 2022-04-06 at 6 43 41 PM](https://user-images.githubusercontent.com/70944781/162128636-5a276b36-2414-4cb2-9093-aab42acb174a.png)
![Screenshot 2022-04-07 at 11 14 05 AM](https://user-images.githubusercontent.com/70944781/162128647-c25821f4-a2f9-4f14-8ba7-7677e8c91cfd.png)


NOW using latest plugin version 2.5.0

**Comment by priyak-sdei** [comment]
I have also raised another bug for the same
https://github.com/weareseeed/react-square-web-payments-sdk/issues/45
